/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : .\\Parser\\PandaSQLSemanticAnalyzer.g
 *     -                            On : 2012-04-22 18:06:56
 *     -           for the tree parser : PandaSQLSemanticAnalyzerTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "PandaSQLSemanticAnalyzer.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pPandaSQLSemanticAnalyzer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pPandaSQLSemanticAnalyzer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pPandaSQLSemanticAnalyzer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pPandaSQLSemanticAnalyzer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO
#undef		SEEK
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger



#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   PandaSQLSemanticAnalyzerTokenNames[13+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "Digit",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "KW_FROM",
        (pANTLR3_UINT8) "KW_SELECT",
        (pANTLR3_UINT8) "KW_TABLE",
        (pANTLR3_UINT8) "Letter",
        (pANTLR3_UINT8) "TOK_ALL_COLUMNS",
        (pANTLR3_UINT8) "TOK_COLUMN_LIST",
        (pANTLR3_UINT8) "TOK_FROM",
        (pANTLR3_UINT8) "TOK_TABLE_NAME",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "';'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	statement    (pPandaSQLSemanticAnalyzer ctx);
static 
 void
	dml_statement    (pPandaSQLSemanticAnalyzer ctx);
static 
 void
	select_statement    (pPandaSQLSemanticAnalyzer ctx);
static 
 void
	select_list    (pPandaSQLSemanticAnalyzer ctx);
static 
 void
	from_clause    (pPandaSQLSemanticAnalyzer ctx);
static 
 PandaSQLSemanticAnalyzer_table_name_return
	table_name    (pPandaSQLSemanticAnalyzer ctx);
static void	PandaSQLSemanticAnalyzerFree(pPandaSQLSemanticAnalyzer ctx);
static void     PandaSQLSemanticAnalyzerReset (pPandaSQLSemanticAnalyzer ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = ".\\Parser\\PandaSQLSemanticAnalyzer.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new PandaSQLSemanticAnalyzer parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pPandaSQLSemanticAnalyzer
PandaSQLSemanticAnalyzerNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return PandaSQLSemanticAnalyzerNewSSD(instream, NULL);
}

/** \brief Create a new PandaSQLSemanticAnalyzer parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pPandaSQLSemanticAnalyzer
PandaSQLSemanticAnalyzerNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pPandaSQLSemanticAnalyzer ctx;	    /* Context structure we will build and return   */

    ctx	= (pPandaSQLSemanticAnalyzer) ANTLR3_CALLOC(1, sizeof(PandaSQLSemanticAnalyzer));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in PandaSQLSemanticAnalyzer.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Install the implementation of our PandaSQLSemanticAnalyzer interface
     */
    ctx->statement	= statement;
    ctx->dml_statement	= dml_statement;
    ctx->select_statement	= select_statement;
    ctx->select_list	= select_list;
    ctx->from_clause	= from_clause;
    ctx->table_name	= table_name;
    ctx->free			= PandaSQLSemanticAnalyzerFree;
    ctx->reset			= PandaSQLSemanticAnalyzerReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = PandaSQLSemanticAnalyzerTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
PandaSQLSemanticAnalyzerReset (pPandaSQLSemanticAnalyzer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 PandaSQLSemanticAnalyzerFree(pPandaSQLSemanticAnalyzer ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
tree parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return PandaSQLSemanticAnalyzerTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dml_statement_in_statement60  */
static	ANTLR3_BITWORD FOLLOW_dml_statement_in_statement60_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_dml_statement_in_statement60	= { FOLLOW_dml_statement_in_statement60_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_select_statement_in_dml_statement72  */
static	ANTLR3_BITWORD FOLLOW_select_statement_in_dml_statement72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_select_statement_in_dml_statement72	= { FOLLOW_select_statement_in_dml_statement72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_KW_SELECT_in_select_statement95  */
static	ANTLR3_BITWORD FOLLOW_KW_SELECT_in_select_statement95_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_KW_SELECT_in_select_statement95	= { FOLLOW_KW_SELECT_in_select_statement95_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_select_list_in_select_statement97  */
static	ANTLR3_BITWORD FOLLOW_select_list_in_select_statement97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_select_list_in_select_statement97	= { FOLLOW_select_list_in_select_statement97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_from_clause_in_select_statement99  */
static	ANTLR3_BITWORD FOLLOW_from_clause_in_select_statement99_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_from_clause_in_select_statement99	= { FOLLOW_from_clause_in_select_statement99_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_COLUMN_LIST_in_select_list116  */
static	ANTLR3_BITWORD FOLLOW_TOK_COLUMN_LIST_in_select_list116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_COLUMN_LIST_in_select_list116	= { FOLLOW_TOK_COLUMN_LIST_in_select_list116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_ALL_COLUMNS_in_select_list118  */
static	ANTLR3_BITWORD FOLLOW_TOK_ALL_COLUMNS_in_select_list118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_ALL_COLUMNS_in_select_list118	= { FOLLOW_TOK_ALL_COLUMNS_in_select_list118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_FROM_in_from_clause135  */
static	ANTLR3_BITWORD FOLLOW_TOK_FROM_in_from_clause135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_FROM_in_from_clause135	= { FOLLOW_TOK_FROM_in_from_clause135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_table_name_in_from_clause139  */
static	ANTLR3_BITWORD FOLLOW_table_name_in_from_clause139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_table_name_in_from_clause139	= { FOLLOW_table_name_in_from_clause139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_TABLE_NAME_in_table_name158  */
static	ANTLR3_BITWORD FOLLOW_TOK_TABLE_NAME_in_table_name158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_TABLE_NAME_in_table_name158	= { FOLLOW_TOK_TABLE_NAME_in_table_name158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_table_name160  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_table_name160_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_table_name160	= { FOLLOW_IDENTIFIER_in_table_name160_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start statement
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:11:1: statement : dml_statement ;
 */
static void
statement(pPandaSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */

    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:12:2: ( dml_statement )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:12:4: dml_statement
        {
            FOLLOWPUSH(FOLLOW_dml_statement_in_statement60);
            dml_statement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start dml_statement
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:15:1: dml_statement : select_statement ;
 */
static void
dml_statement(pPandaSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */

    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:16:2: ( select_statement )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:16:4: select_statement
        {
            FOLLOWPUSH(FOLLOW_select_statement_in_dml_statement72);
            select_statement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledml_statementEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledml_statementEx; /* Prevent compiler warnings */
    ruledml_statementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end dml_statement */

/**
 * $ANTLR start select_statement
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:19:1: select_statement : ^( KW_SELECT select_list from_clause ) ;
 */
static void
select_statement(pPandaSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */


    	printf("***select_statement begin***\n");

    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:28:2: ( ^( KW_SELECT select_list from_clause ) )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:28:4: ^( KW_SELECT select_list from_clause )
        {
             MATCHT(KW_SELECT, &FOLLOW_KW_SELECT_in_select_statement95);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }

            FOLLOWPUSH(FOLLOW_select_list_in_select_statement97);
            select_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            FOLLOWPUSH(FOLLOW_from_clause_in_select_statement99);
            from_clause(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }



            {

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleselect_statementEx; /* Prevent compiler warnings */
    ruleselect_statementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {

                    	printf("***select_statement end***\n");

                }
            }


    return ;
}
/* $ANTLR end select_statement */

/**
 * $ANTLR start select_list
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:33:1: select_list : ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS ) ;
 */
static void
select_list(pPandaSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */

    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:34:2: ( ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS ) )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:34:4: ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS )
        {
             MATCHT(TOK_COLUMN_LIST, &FOLLOW_TOK_COLUMN_LIST_in_select_list116);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }

             MATCHT(TOK_ALL_COLUMNS, &FOLLOW_TOK_ALL_COLUMNS_in_select_list118);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }



            {

                		printf("selectList: *\n");
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleselect_listEx; /* Prevent compiler warnings */
    ruleselect_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end select_list */

/**
 * $ANTLR start from_clause
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:40:1: from_clause : ^( TOK_FROM tableName= table_name ) ;
 */
static void
from_clause(pPandaSQLSemanticAnalyzer ctx)
{
    PandaSQLSemanticAnalyzer_table_name_return tableName;
    #undef	RETURN_TYPE_tableName
    #define	RETURN_TYPE_tableName PandaSQLSemanticAnalyzer_table_name_return

    /* Initialize rule variables
     */

    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:41:2: ( ^( TOK_FROM tableName= table_name ) )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:41:4: ^( TOK_FROM tableName= table_name )
        {
             MATCHT(TOK_FROM, &FOLLOW_TOK_FROM_in_from_clause135);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }

            FOLLOWPUSH(FOLLOW_table_name_in_from_clause139);
            tableName=table_name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }



            {

                		printf("tableName: %s\n", (STRSTREAM->toStringSS(STRSTREAM, tableName.start, tableName.start))
                ->chars);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefrom_clauseEx; /* Prevent compiler warnings */
    rulefrom_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end from_clause */

/**
 * $ANTLR start table_name
 * .\\Parser\\PandaSQLSemanticAnalyzer.g:47:1: table_name : ^( TOK_TABLE_NAME IDENTIFIER ) ;
 */
static PandaSQLSemanticAnalyzer_table_name_return
table_name(pPandaSQLSemanticAnalyzer ctx)
{
    PandaSQLSemanticAnalyzer_table_name_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:48:2: ( ^( TOK_TABLE_NAME IDENTIFIER ) )
        // .\\Parser\\PandaSQLSemanticAnalyzer.g:48:4: ^( TOK_TABLE_NAME IDENTIFIER )
        {
             MATCHT(TOK_TABLE_NAME, &FOLLOW_TOK_TABLE_NAME_in_table_name158);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }

             MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_table_name160);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }



            {

                		
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletable_nameEx; /* Prevent compiler warnings */
    ruletable_nameEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end table_name */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
