/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : .\\Parser\\SQLSemanticAnalyzer.g
 *     -                            On : 2012-04-23 01:20:42
 *     -           for the tree parser : SQLSemanticAnalyzerTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */



#include "Parser/SQLParserDriver.h"



/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SQLSemanticAnalyzer.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSQLSemanticAnalyzer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSQLSemanticAnalyzer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSQLSemanticAnalyzer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSQLSemanticAnalyzer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO
#undef		SEEK
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger



#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */

/* ruleAttributeScopeFuncDecl(scope)
 */
/* -----------------------------------------------------------------------------
 * Function declarations for creating a SQLSemanticAnalyzer_statement scope set
 */
static pSQLSemanticAnalyzer_statement_SCOPE   pSQLSemanticAnalyzer_statementPush(pSQLSemanticAnalyzer ctx);
static void ANTLR3_CDECL statementFree(pSQLSemanticAnalyzer_statement_SCOPE scope);
/* ----------------------------------------------------------------------------- */


/* ruleAttributeScopeFuncs(scope)
 */
/* attributeFuncs(scope)
 */

static void ANTLR3_CDECL statementFree(pSQLSemanticAnalyzer_statement_SCOPE scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Allocate initial memory for a SQLSemanticAnalyzer statement scope variable stack entry and
 *         add it to the top of the stack.
 *
 * \remark
 * By default the structure is freed with ANTLR_FREE(), but you can use the
 * the \@init action to install a pointer to a custom free() routine by
 * adding the code:
 * \code
 *   ctx->pSQLSemanticAnalyzer_statementTop->free = myroutine;
 * \endcode
 *
 * With lots of comments of course! The routine should be declared in
 * \@members { } as:
 * \code
 *   void ANTLR3_CDECL myfunc( pSQLSemanticAnalyzer_statement_SCOPE ptr).
 * \endcode
 *
 * It should perform any custom freeing stuff that you need (call ANTLR_FREE3, not free()
 * NB: It should not free the pointer it is given, which is the scope stack entry itself
 * and will be freed by the function that calls your custom free routine.
 *
 */
static pSQLSemanticAnalyzer_statement_SCOPE
pSQLSemanticAnalyzer_statementPush(pSQLSemanticAnalyzer ctx)
{
    /* Pointer used to create a new set of attributes
     */
    pSQLSemanticAnalyzer_statement_SCOPE      newAttributes;

    /* Allocate the memory for a new structure if we need one.
     */
    if (ctx->pSQLSemanticAnalyzer_statementStack->size(ctx->pSQLSemanticAnalyzer_statementStack) > ctx->pSQLSemanticAnalyzer_statementStack_limit)
    {
        // The current limit value was less than the number of scopes available on the stack so
        // we can just reuse one. Our limit tracks the stack count, so the index of the entry we want
        // is one less than that, or conveniently, the current value of limit.
        //
        newAttributes = (pSQLSemanticAnalyzer_statement_SCOPE)ctx->pSQLSemanticAnalyzer_statementStack->get(ctx->pSQLSemanticAnalyzer_statementStack, ctx->pSQLSemanticAnalyzer_statementStack_limit);
    }
    else
    {
        // Need a new allocation
        //
        newAttributes = (pSQLSemanticAnalyzer_statement_SCOPE) ANTLR3_MALLOC(sizeof(SQLSemanticAnalyzer_statement_SCOPE));
        if  (newAttributes != NULL)
        {
            /* Standard ANTLR3 library implementation
             */
            ctx->pSQLSemanticAnalyzer_statementStack->push(ctx->pSQLSemanticAnalyzer_statementStack, newAttributes, (void (*)(void *))statementFree);
        }
    }

    // Blank out any previous free pointer, the user might or might install a new one.
    //
    newAttributes->free = NULL;

    // Indicate the position in the available stack that the current level is at
    //
    ctx->pSQLSemanticAnalyzer_statementStack_limit++;

	/* Return value is the pointer to the new entry, which may be used locally
	 * without de-referencing via the context.
     */
    return  newAttributes;
}







/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   SQLSemanticAnalyzerTokenNames[13+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "Digit",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "KW_FROM",
        (pANTLR3_UINT8) "KW_SELECT",
        (pANTLR3_UINT8) "KW_TABLE",
        (pANTLR3_UINT8) "Letter",
        (pANTLR3_UINT8) "TOK_ALL_COLUMNS",
        (pANTLR3_UINT8) "TOK_COLUMN_LIST",
        (pANTLR3_UINT8) "TOK_FROM",
        (pANTLR3_UINT8) "TOK_TABLE_NAME",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "';'"
       };


/* ruleAttributeScopeFuncMacro(scope)
 */
/** Function for popping the top value from a pSQLSemanticAnalyzer_statementStack
 */
void
pSQLSemanticAnalyzer_statementPop(pSQLSemanticAnalyzer ctx)
{
    // First see if the user defined a function they want to be called when a
    // scope is popped/freed.
    //
	// If the user supplied the scope entries with a free function,then call it first
	//
    if	(SCOPE_TOP(statement)->free != NULL)
	{
        SCOPE_TOP(statement)->free(SCOPE_TOP(statement));
	}

    // Now we decrement the scope's upper limit bound. We do not actually pop the scope as
    // we want to reuse scope entries if we do continuous push and pops. Most scopes don't
    // next too far so we don't want to keep freeing and allocating them
    //
    ctx->pSQLSemanticAnalyzer_statementStack_limit--;
    SCOPE_TOP(statement) = (pSQLSemanticAnalyzer_statement_SCOPE)(ctx->pSQLSemanticAnalyzer_statementStack->get(ctx->pSQLSemanticAnalyzer_statementStack, ctx->pSQLSemanticAnalyzer_statementStack_limit - 1));
}



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	statement    (pSQLSemanticAnalyzer ctx, PandaSQL::SQLParserDriver *io_pDriver);
static 
 void
	dml_statement    (pSQLSemanticAnalyzer ctx);
static 
 void
	select_statement    (pSQLSemanticAnalyzer ctx);
static 
 void
	select_list    (pSQLSemanticAnalyzer ctx);
static 
 void
	from_clause    (pSQLSemanticAnalyzer ctx);
static 
 SQLSemanticAnalyzer_table_name_return
	table_name    (pSQLSemanticAnalyzer ctx);
static void	SQLSemanticAnalyzerFree(pSQLSemanticAnalyzer ctx);
static void     SQLSemanticAnalyzerReset (pSQLSemanticAnalyzer ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = ".\\Parser\\SQLSemanticAnalyzer.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new SQLSemanticAnalyzer parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSQLSemanticAnalyzer
SQLSemanticAnalyzerNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return SQLSemanticAnalyzerNewSSD(instream, NULL);
}

/** \brief Create a new SQLSemanticAnalyzer parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSQLSemanticAnalyzer
SQLSemanticAnalyzerNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSQLSemanticAnalyzer ctx;	    /* Context structure we will build and return   */

    ctx	= (pSQLSemanticAnalyzer) ANTLR3_CALLOC(1, sizeof(SQLSemanticAnalyzer));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in SQLSemanticAnalyzer.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Install the implementation of our SQLSemanticAnalyzer interface
     */
    ctx->statement	= statement;
    ctx->dml_statement	= dml_statement;
    ctx->select_statement	= select_statement;
    ctx->select_list	= select_list;
    ctx->from_clause	= from_clause;
    ctx->table_name	= table_name;
    ctx->free			= SQLSemanticAnalyzerFree;
    ctx->reset			= SQLSemanticAnalyzerReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pSQLSemanticAnalyzer_statementPush     = pSQLSemanticAnalyzer_statementPush;
    ctx->pSQLSemanticAnalyzer_statementStack    = antlr3StackNew(0);
    ctx->pSQLSemanticAnalyzer_statementStack_limit    = 0;
    ctx->pSQLSemanticAnalyzer_statementTop      = NULL;




    /* Install the token table
     */
    PSRSTATE->tokenNames   = SQLSemanticAnalyzerTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
SQLSemanticAnalyzerReset (pSQLSemanticAnalyzer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 SQLSemanticAnalyzerFree(pSQLSemanticAnalyzer ctx)
 {
    /* Free any scope memory
     */
    /* ruleAttributeScope(scope)
     */
    ctx->pSQLSemanticAnalyzer_statementStack->free(ctx->pSQLSemanticAnalyzer_statementStack);



	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
tree parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return SQLSemanticAnalyzerTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dml_statement_in_statement79  */
static	ANTLR3_BITWORD FOLLOW_dml_statement_in_statement79_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_dml_statement_in_statement79	= { FOLLOW_dml_statement_in_statement79_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_select_statement_in_dml_statement91  */
static	ANTLR3_BITWORD FOLLOW_select_statement_in_dml_statement91_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_select_statement_in_dml_statement91	= { FOLLOW_select_statement_in_dml_statement91_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_KW_SELECT_in_select_statement114  */
static	ANTLR3_BITWORD FOLLOW_KW_SELECT_in_select_statement114_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_KW_SELECT_in_select_statement114	= { FOLLOW_KW_SELECT_in_select_statement114_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_select_list_in_select_statement116  */
static	ANTLR3_BITWORD FOLLOW_select_list_in_select_statement116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_select_list_in_select_statement116	= { FOLLOW_select_list_in_select_statement116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_from_clause_in_select_statement118  */
static	ANTLR3_BITWORD FOLLOW_from_clause_in_select_statement118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_from_clause_in_select_statement118	= { FOLLOW_from_clause_in_select_statement118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_COLUMN_LIST_in_select_list135  */
static	ANTLR3_BITWORD FOLLOW_TOK_COLUMN_LIST_in_select_list135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_COLUMN_LIST_in_select_list135	= { FOLLOW_TOK_COLUMN_LIST_in_select_list135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_ALL_COLUMNS_in_select_list137  */
static	ANTLR3_BITWORD FOLLOW_TOK_ALL_COLUMNS_in_select_list137_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_ALL_COLUMNS_in_select_list137	= { FOLLOW_TOK_ALL_COLUMNS_in_select_list137_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_FROM_in_from_clause154  */
static	ANTLR3_BITWORD FOLLOW_TOK_FROM_in_from_clause154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_FROM_in_from_clause154	= { FOLLOW_TOK_FROM_in_from_clause154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_table_name_in_from_clause158  */
static	ANTLR3_BITWORD FOLLOW_table_name_in_from_clause158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_table_name_in_from_clause158	= { FOLLOW_table_name_in_from_clause158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TOK_TABLE_NAME_in_table_name177  */
static	ANTLR3_BITWORD FOLLOW_TOK_TABLE_NAME_in_table_name177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_TOK_TABLE_NAME_in_table_name177	= { FOLLOW_TOK_TABLE_NAME_in_table_name177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_table_name179  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_table_name179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_table_name179	= { FOLLOW_IDENTIFIER_in_table_name179_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start statement
 * .\\Parser\\SQLSemanticAnalyzer.g:20:1: statement[PandaSQL::SQLParserDriver *io_pDriver] : dml_statement ;
 */
static void
statement(pSQLSemanticAnalyzer ctx, PandaSQL::SQLParserDriver *io_pDriver)
{
    /* Initialize rule variables
     */
    ctx->pSQLSemanticAnalyzer_statementTop = pSQLSemanticAnalyzer_statementPush(ctx);

    	(SCOPE_TOP(statement))->pDriver= io_pDriver;

    {
        // .\\Parser\\SQLSemanticAnalyzer.g:29:2: ( dml_statement )
        // .\\Parser\\SQLSemanticAnalyzer.g:29:4: dml_statement
        {
            FOLLOWPUSH(FOLLOW_dml_statement_in_statement79);
            dml_statement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    pSQLSemanticAnalyzer_statementPop(ctx);

    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start dml_statement
 * .\\Parser\\SQLSemanticAnalyzer.g:32:1: dml_statement : select_statement ;
 */
static void
dml_statement(pSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */

    {
        // .\\Parser\\SQLSemanticAnalyzer.g:33:2: ( select_statement )
        // .\\Parser\\SQLSemanticAnalyzer.g:33:4: select_statement
        {
            FOLLOWPUSH(FOLLOW_select_statement_in_dml_statement91);
            select_statement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledml_statementEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledml_statementEx; /* Prevent compiler warnings */
    ruledml_statementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end dml_statement */

/**
 * $ANTLR start select_statement
 * .\\Parser\\SQLSemanticAnalyzer.g:36:1: select_statement : ^( KW_SELECT select_list from_clause ) ;
 */
static void
select_statement(pSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */


    	printf("***select_statement begin***\n");

    {
        // .\\Parser\\SQLSemanticAnalyzer.g:45:2: ( ^( KW_SELECT select_list from_clause ) )
        // .\\Parser\\SQLSemanticAnalyzer.g:45:4: ^( KW_SELECT select_list from_clause )
        {
             MATCHT(KW_SELECT, &FOLLOW_KW_SELECT_in_select_statement114);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }

            FOLLOWPUSH(FOLLOW_select_list_in_select_statement116);
            select_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            FOLLOWPUSH(FOLLOW_from_clause_in_select_statement118);
            from_clause(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }



            {

                		PandaSQL::SQLParserDriver *pDriver = (SCOPE_TOP(statement))->pDriver;
                		pDriver->PrintCurrentState();
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleselect_statementEx; /* Prevent compiler warnings */
    ruleselect_statementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
            else
            {
                {

                    	printf("***select_statement end***\n");

                }
            }


    return ;
}
/* $ANTLR end select_statement */

/**
 * $ANTLR start select_list
 * .\\Parser\\SQLSemanticAnalyzer.g:52:1: select_list : ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS ) ;
 */
static void
select_list(pSQLSemanticAnalyzer ctx)
{
    /* Initialize rule variables
     */

    {
        // .\\Parser\\SQLSemanticAnalyzer.g:53:2: ( ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS ) )
        // .\\Parser\\SQLSemanticAnalyzer.g:53:4: ^( TOK_COLUMN_LIST TOK_ALL_COLUMNS )
        {
             MATCHT(TOK_COLUMN_LIST, &FOLLOW_TOK_COLUMN_LIST_in_select_list135);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }

             MATCHT(TOK_ALL_COLUMNS, &FOLLOW_TOK_ALL_COLUMNS_in_select_list137);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleselect_listEx;
            }



            {

                		printf("selectList: *\n");
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleselect_listEx; /* Prevent compiler warnings */
    ruleselect_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end select_list */

/**
 * $ANTLR start from_clause
 * .\\Parser\\SQLSemanticAnalyzer.g:59:1: from_clause : ^( TOK_FROM tableName= table_name ) ;
 */
static void
from_clause(pSQLSemanticAnalyzer ctx)
{
    SQLSemanticAnalyzer_table_name_return tableName;
    #undef	RETURN_TYPE_tableName
    #define	RETURN_TYPE_tableName SQLSemanticAnalyzer_table_name_return

    /* Initialize rule variables
     */

    {
        // .\\Parser\\SQLSemanticAnalyzer.g:60:2: ( ^( TOK_FROM tableName= table_name ) )
        // .\\Parser\\SQLSemanticAnalyzer.g:60:4: ^( TOK_FROM tableName= table_name )
        {
             MATCHT(TOK_FROM, &FOLLOW_TOK_FROM_in_from_clause154);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }

            FOLLOWPUSH(FOLLOW_table_name_in_from_clause158);
            tableName=table_name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefrom_clauseEx;
            }



            {

                		printf("tableName: %s\n", (STRSTREAM->toStringSS(STRSTREAM, tableName.start, tableName.start))
                ->chars);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefrom_clauseEx; /* Prevent compiler warnings */
    rulefrom_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end from_clause */

/**
 * $ANTLR start table_name
 * .\\Parser\\SQLSemanticAnalyzer.g:66:1: table_name : ^( TOK_TABLE_NAME IDENTIFIER ) ;
 */
static SQLSemanticAnalyzer_table_name_return
table_name(pSQLSemanticAnalyzer ctx)
{
    SQLSemanticAnalyzer_table_name_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // .\\Parser\\SQLSemanticAnalyzer.g:67:2: ( ^( TOK_TABLE_NAME IDENTIFIER ) )
        // .\\Parser\\SQLSemanticAnalyzer.g:67:4: ^( TOK_TABLE_NAME IDENTIFIER )
        {
             MATCHT(TOK_TABLE_NAME, &FOLLOW_TOK_TABLE_NAME_in_table_name177);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }

             MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_table_name179);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }



            {

                		
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletable_nameEx; /* Prevent compiler warnings */
    ruletable_nameEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end table_name */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
